from .auth import router as auth_router
from .donation import router as donation_router
from .event import router as event_router
from .gallery import router as gallery_router
from .lead import router as lead_router
from .team_member import router as team_member_router
from .images import router as images_router
from .project import router as project_router
from .settings import router as settings_router
